# Generated by Django 3.0.4 on 2020-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping'),
        ),
    ]
